---
- name: install_coreos
  hosts: 
    - bootstrap
    - master
    - worker
  vars:
    ansible_ssh_private_key_file: ~/.ssh/scaleway
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars_files:
    - ../variables.yaml
  roles:
    - ../roles/install_coreos
